export const CREATE_TASK = 'CREATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS'
export const CHANGE_COMP_TO_INCOMP = 'CHANGE_COMP_TO_INCOMP'
export const CHANGE_INCOMP_TO_COMP = 'CHANGE_INCOMP_TO_COMP'

export const ADD_OPERATION_LOG =  'ADD_OPERATION_LOG'
export const DELETE_ALL_OPERATION_LOGS =  'DELETE_ALL_OPERATION_LOGS'